"""Deterministic Project Wiki and harness synchronization.

Runs as the Claude Code ``Stop`` hook after every work turn. Regenerates the
machine-owned wiki pages under ``Project Wiki/_generated/``, rewrites the
AUTO-marked blocks in ``Project Wiki/02 Architecture/Module Dependency
Graph.md``, ``CLAUDE.md``, and the root ``MEMORY.md``, then mirrors the
harness via ``scripts/sync_harness.py`` so ``CLAUDE.md`` and ``AGENTS.md``
never drift.

Design constraints:

- Pure standard library, no LLM calls: output is a deterministic function of
  the repository state.
- Idempotent: a second run over an unchanged repository produces zero diff.
  Timestamps only change when the surrounding content changes.
- Never blocks the agent: the process always exits 0; any internal failure is
  recorded in ``Project Wiki/_generated/Drift Report.md`` instead of raised.
"""

import ast
import datetime
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WIKI = ROOT / "Project Wiki"
GENERATED = WIKI / "_generated"

# Packages scanned for module inventory and the dependency graph.
PACKAGES = ["capstone_agent", "clinical_app", "mcp_server", "scripts", "tests"]

# Volatile lines ignored when deciding whether a page actually changed, so
# timestamps do not defeat idempotency.
VOLATILE = re.compile(r"^(updated:|- Last synced:).*$", re.MULTILINE)

errors: list[str] = []


def today() -> str:
    """Return the current date as YYYY-MM-DD for frontmatter timestamps."""
    return datetime.date.today().isoformat()


def write_if_changed(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` only when the non-volatile parts differ.

    Returns True when the file was (re)written. Keeping unchanged files
    untouched is what makes the sync idempotent and diff-friendly.
    """
    if path.exists():
        old = path.read_text(encoding="utf-8")
        if VOLATILE.sub("", old) == VOLATILE.sub("", content):
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    return True


def first_docstring_line(py_path: Path) -> str:
    """Extract the first line of a module's docstring, or a placeholder."""
    try:
        tree = ast.parse(py_path.read_text(encoding="utf-8"))
        doc = ast.get_docstring(tree)
        if doc:
            return doc.strip().splitlines()[0].strip()
    except Exception as exc:  # syntax errors must not kill the sync
        errors.append(f"docstring parse failed for {py_path.name}: {exc}")
    return "(no docstring)"


def list_modules() -> list[tuple[str, str, str]]:
    """Return (package, module filename, purpose) for every project module."""
    rows = []
    for pkg in PACKAGES:
        pkg_dir = ROOT / pkg
        if not pkg_dir.is_dir():
            continue
        for py in sorted(pkg_dir.glob("*.py")):
            rows.append((pkg, py.name, first_docstring_line(py)))
    return rows


def replace_between(text: str, begin: str, end: str, replacement: str) -> str:
    """Replace the region between two marker lines, keeping the markers."""
    pattern = re.compile(
        re.escape(begin) + r".*?" + re.escape(end), re.DOTALL
    )
    if not pattern.search(text):
        raise ValueError(f"markers not found: {begin}")
    return pattern.sub(begin + "\n" + replacement.strip("\n") + "\n" + end, text)


def sync_module_inventory(modules: list[tuple[str, str, str]]) -> None:
    """Rewrite the Module Inventory page and per-module stub notes."""
    lines = [
        "---",
        "title: Module Inventory",
        "type: generated",
        f"updated: {today()}",
        "tags:",
        "  - generated",
        "---",
        "",
        "# Module Inventory",
        "",
        "Machine-generated by `scripts/sync_wiki.py`. Do not hand-edit.",
        "Hand-written companion: [[Module Reference]].",
        "",
        "| Package | Module | Purpose |",
        "|---------|--------|---------|",
    ]
    for pkg, name, purpose in modules:
        lines.append(f"| `{pkg}` | `{name}` | {purpose} |")
    write_if_changed(GENERATED / "Module Inventory.md", "\n".join(lines) + "\n")

    # Per-module stubs feed the Modules.base table views.
    mod_dir = GENERATED / "modules"
    expected = set()
    for pkg, name, purpose in modules:
        stem = f"{pkg}.{name[:-3]}"
        expected.add(f"{stem}.md")
        note = "\n".join(
            [
                "---",
                f"title: {pkg}/{name}",
                "type: module",
                f"package: {pkg}",
                f'purpose: "{purpose.replace(chr(34), chr(39))}"',
                f"updated: {today()}",
                "---",
                "",
                f"# {pkg}/{name}",
                "",
                purpose,
                "",
                "Generated by `scripts/sync_wiki.py`; see [[Module Reference]].",
            ]
        ) + "\n"
        write_if_changed(mod_dir / f"{stem}.md", note)
    # Remove stubs for modules that no longer exist (machine-owned dir only).
    if mod_dir.is_dir():
        for stale in mod_dir.glob("*.md"):
            if stale.name not in expected:
                stale.unlink()


def build_depgraph_mermaid() -> str:
    """Build a Mermaid flowchart of intra-package capstone_agent imports."""
    pkg_dir = ROOT / "capstone_agent"
    names = {p.stem for p in pkg_dir.glob("*.py") if p.stem != "__init__"}
    edges = set()
    for py in sorted(pkg_dir.glob("*.py")):
        if py.stem == "__init__":
            continue
        try:
            tree = ast.parse(py.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"import parse failed for {py.name}: {exc}")
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module:
                mod = node.module.split(".")[-1]
                if node.module.startswith("capstone_agent") and mod in names:
                    if mod != py.stem:
                        edges.add((mod, py.stem))
                elif node.level >= 1 and mod in names and mod != py.stem:
                    edges.add((mod, py.stem))
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    parts = alias.name.split(".")
                    if parts[0] == "capstone_agent" and len(parts) > 1:
                        if parts[1] in names and parts[1] != py.stem:
                            edges.add((parts[1], py.stem))
    used = sorted({n for edge in edges for n in edge})
    lines = ["```mermaid", "flowchart LR"]
    for name in used:
        lines.append(f"    {name}[{name}.py]")
    lines.append("")
    for src, dst in sorted(edges):
        lines.append(f"    {src} --> {dst}")
    lines.append("```")
    return "\n".join(lines)


def sync_depgraph() -> None:
    """Rewrite the AUTO:DEPGRAPH block in the dependency graph note."""
    page = WIKI / "02 Architecture" / "Module Dependency Graph.md"
    if not page.exists():
        errors.append("Module Dependency Graph.md missing; depgraph skipped")
        return
    text = page.read_text(encoding="utf-8")
    try:
        new = replace_between(
            text,
            "<!-- AUTO:DEPGRAPH:BEGIN -->",
            "<!-- AUTO:DEPGRAPH:END -->",
            build_depgraph_mermaid(),
        )
    except ValueError as exc:
        errors.append(str(exc))
        return
    if new != text:
        with open(page, "w", encoding="utf-8", newline="\n") as f:
            f.write(new)


def count_tests() -> list[tuple[str, int, str]]:
    """Return (test file, test function count, purpose) per tests/ module."""
    rows = []
    for py in sorted((ROOT / "tests").glob("test_*.py")):
        try:
            tree = ast.parse(py.read_text(encoding="utf-8"))
            count = sum(
                isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
                and n.name.startswith("test_")
                for n in ast.walk(tree)
            )
        except Exception as exc:
            errors.append(f"test parse failed for {py.name}: {exc}")
            count = 0
        rows.append((py.name, count, first_docstring_line(py)))
    return rows


def sync_test_inventory() -> int:
    """Rewrite the Test Inventory page; return the total test count."""
    rows = count_tests()
    total = sum(count for _, count, _ in rows)
    lines = [
        "---",
        "title: Test Inventory",
        "type: generated",
        f"updated: {today()}",
        "tags:",
        "  - generated",
        "---",
        "",
        "# Test Inventory",
        "",
        "Machine-generated by `scripts/sync_wiki.py`. Do not hand-edit.",
        "Hand-written companion: [[Testing & Eval]].",
        "",
        "| Test file | Tests | Covers |",
        "|-----------|-------|--------|",
    ]
    for name, count, purpose in rows:
        lines.append(f"| `{name}` | {count} | {purpose} |")
    lines.append("")
    lines.append(f"**Total test functions: {total}**")
    write_if_changed(GENERATED / "Test Inventory.md", "\n".join(lines) + "\n")
    return total


def sync_harness_index() -> None:
    """Rewrite the Harness Index page from the actual .claude/ contents."""
    lines = [
        "---",
        "title: Harness Index",
        "type: generated",
        f"updated: {today()}",
        "tags:",
        "  - generated",
        "---",
        "",
        "# Harness Index",
        "",
        "Machine-generated by `scripts/sync_wiki.py`. Do not hand-edit.",
        "Hand-written companion: [[Claude Harness]].",
        "",
    ]
    claude = ROOT / ".claude"
    for section in ["rules", "commands", "references"]:
        folder = claude / section
        lines.append(f"## {section}")
        lines.append("")
        if folder.is_dir():
            for f in sorted(folder.glob("*.md")):
                lines.append(f"- `.claude/{section}/{f.name}`")
        lines.append("")
    lines.append("## skills")
    lines.append("")
    skills = claude / "skills"
    if skills.is_dir():
        for d in sorted(p for p in skills.iterdir() if p.is_dir()):
            lines.append(f"- `.claude/skills/{d.name}/SKILL.md`")
    lines.append("")
    write_if_changed(GENERATED / "Harness Index.md", "\n".join(lines) + "\n")


def git_lines(args: list[str]) -> list[str]:
    """Run a git command at the repo root and return stdout lines."""
    try:
        out = subprocess.run(
            ["git", *args], cwd=ROOT, capture_output=True, text=True,
            encoding="utf-8", timeout=10,
        )
        return out.stdout.strip().splitlines() if out.returncode == 0 else []
    except Exception as exc:
        errors.append(f"git {' '.join(args)} failed: {exc}")
        return []


def sync_changelog() -> str:
    """Rewrite the Changelog page from recent commits; return HEAD hash."""
    commits = git_lines(["log", "-15", "--oneline"])
    head = git_lines(["rev-parse", "--short", "HEAD"])
    branch = git_lines(["branch", "--show-current"])
    lines = [
        "---",
        "title: Changelog",
        "type: generated",
        f"updated: {today()}",
        "tags:",
        "  - generated",
        "---",
        "",
        "# Changelog",
        "",
        "Machine-generated by `scripts/sync_wiki.py`. Do not hand-edit.",
        "",
        f"Branch: `{branch[0] if branch else 'unknown'}` · "
        f"HEAD: `{head[0] if head else 'unknown'}`",
        "",
        "## Recent commits",
        "",
    ]
    lines += [f"- `{c}`" for c in commits] or ["- (no git history available)"]
    lines.append("")
    write_if_changed(GENERATED / "Changelog.md", "\n".join(lines) + "\n")
    return head[0] if head else "unknown"


def build_structure_tree(modules: list[tuple[str, str, str]]) -> str:
    """Render the Project Structure tree for the CLAUDE.md AUTO block."""
    lines = ["```"]
    for pkg in PACKAGES:
        pkg_dir = ROOT / pkg
        if not pkg_dir.is_dir():
            continue
        lines.append(f"{pkg}/")
        for p, name, purpose in modules:
            if p == pkg and name != "__init__.py":
                pad = " " * max(1, 26 - len(name))
                note = purpose if purpose != "(no docstring)" else ""
                lines.append(f"  {name}{pad}# {note}".rstrip(" #").rstrip())
    for extra, note in [
        ("frontend/", "React/Vite/TypeScript clinical UI (16 routes)"),
        ("eval/", "ADK evaluation suite (evalset + scoring config)"),
        ("deployment/", "Dockerfile, cloudbuild.yaml, Agent Engine config"),
        ("docs/", "Architecture and product documentation"),
        ("Project Wiki/", "Obsidian knowledge base (auto-synced)"),
    ]:
        pad = " " * max(1, 28 - len(extra))
        lines.append(f"{extra}{pad}# {note}")
    lines.append("```")
    return "\n".join(lines)


def sync_claude_md(modules: list[tuple[str, str, str]]) -> None:
    """Rewrite the AUTO:STRUCTURE block inside CLAUDE.md."""
    claude_md = ROOT / "CLAUDE.md"
    if not claude_md.exists():
        errors.append("CLAUDE.md missing; structure sync skipped")
        return
    text = claude_md.read_text(encoding="utf-8")
    try:
        new = replace_between(
            text,
            "<!-- AUTO:STRUCTURE:BEGIN -->",
            "<!-- AUTO:STRUCTURE:END -->",
            build_structure_tree(modules),
        )
    except ValueError as exc:
        errors.append(str(exc))
        return
    if new != text:
        with open(claude_md, "w", encoding="utf-8", newline="\n") as f:
            f.write(new)


def parse_model_tiers() -> list[str]:
    """Extract tier names from MODEL_TIERS in capstone_agent/llm.py."""
    llm_py = ROOT / "capstone_agent" / "llm.py"
    tiers = []
    try:
        tree = ast.parse(llm_py.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            targets = []
            if isinstance(node, ast.Assign):
                targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
            elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
                targets = [node.target.id]
            if "MODEL_TIERS" in targets and isinstance(node.value, ast.Dict):
                for key in node.value.keys:
                    if isinstance(key, ast.Constant) and isinstance(key.value, str):
                        tiers.append(key.value)
    except Exception as exc:
        errors.append(f"MODEL_TIERS parse failed: {exc}")
    return tiers


def sync_memory_md(module_count: int, test_total: int, head: str) -> None:
    """Create or refresh the root MEMORY.md workspace register file."""
    tiers = parse_model_tiers()
    content = "\n".join(
        [
            "# Developer Agent Memory",
            "",
            "Workspace variables and active model registers for the Google",
            "Capstone Project. The AUTO block below is maintained by",
            "`scripts/sync_wiki.py` (Stop hook); do not hand-edit inside the",
            "markers. Durable cross-session facts live in the Claude Code",
            "auto-memory directory, and harness memory placeholders live in",
            "`.claude/memory/`.",
            "",
            "<!-- AUTO:REGISTERS:BEGIN -->",
            f"- Python modules tracked: {module_count}",
            f"- Test functions: {test_total}",
            f"- Model tiers (llm.MODEL_TIERS): {', '.join(tiers) or 'unknown'}",
            f"- Git HEAD: {head}",
            f"- Last synced: {today()}",
            "<!-- AUTO:REGISTERS:END -->",
            "",
            "See `Project Wiki/Home.md` for the full knowledge base.",
        ]
    ) + "\n"
    write_if_changed(ROOT / "MEMORY.md", content)


def sync_drift_report(modules: list[tuple[str, str, str]]) -> None:
    """Flag modules not referenced anywhere in hand-written wiki notes."""
    corpus = ""
    for md in WIKI.rglob("*.md"):
        if GENERATED in md.parents:
            continue
        corpus += md.read_text(encoding="utf-8")
    unlinked = [
        f"`{pkg}/{name}`"
        for pkg, name, _ in modules
        if name != "__init__.py" and name not in corpus
    ]
    lines = [
        "---",
        "title: Drift Report",
        "type: generated",
        f"updated: {today()}",
        "tags:",
        "  - generated",
        "---",
        "",
        "# Drift Report",
        "",
        "Machine-generated by `scripts/sync_wiki.py`. Items here need a human",
        "(or Claude) to update the hand-written wiki pages.",
        "",
        "## Modules missing from hand-written notes",
        "",
    ]
    lines += [f"- {m}" for m in unlinked] or ["- none — wiki covers all modules"]
    lines += ["", "## Sync warnings", ""]
    lines += [f"- {e}" for e in errors] or ["- none"]
    lines.append("")
    write_if_changed(GENERATED / "Drift Report.md", "\n".join(lines) + "\n")


def main() -> None:
    """Run the full deterministic sync; never raise, always exit 0."""
    try:
        modules = list_modules()
        sync_module_inventory(modules)
        sync_depgraph()
        test_total = sync_test_inventory()
        sync_harness_index()
        head = sync_changelog()
        sync_claude_md(modules)
        sync_memory_md(
            sum(1 for _, n, _ in modules if n != "__init__.py"),
            test_total,
            head,
        )
        sync_drift_report(modules)
        # Mirror .claude/ -> .agents/ and CLAUDE.md -> AGENTS.md so
        # check_harness.py keeps passing after the CLAUDE.md rewrite.
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        import sync_harness

        sync_harness.sync_harness()
        print("Wiki sync complete.")
    except Exception as exc:
        # A Stop hook must never block the agent; surface the failure in the
        # drift report location if possible and still exit cleanly.
        print(f"Wiki sync failed: {exc}", file=sys.stderr)
    sys.exit(0)


if __name__ == "__main__":
    main()
